NCIC_OFFENSE_CODES = {
    "0101": "Arson",
    "0201": "Assault - Aggravated - Firearm",
    "0202": "Assault - Aggravated - Knife",
    "0203": "Assault - Aggravated - Other",
    "0204": "Assault - Aggravated - Hands/Fists",
    "0205": "Assault - Simple",
    "0206": "Assault - Intimidation",
    "0301": "Burglary - Forced Entry - Residence",
    "0302": "Burglary - Forced Entry - Non-Residence",
    "0303": "Burglary - Unlawful Entry - Residence",
    "0304": "Burglary - Unlawful Entry - Non-Residence",
    "0401": "Counterfeiting/Forgery",
    "0501": "Destruction/Vandalism of Property",
    "0601": "Drug/Narcotic Violations - Possession",
    "0602": "Drug/Narcotic Violations - Sale/Manufacturing",
    "0603": "Drug Equipment Violations",
    "0701": "Embezzlement",
    "0801": "Extortion/Blackmail",
    "0901": "Fraud - False Pretenses",
    "0902": "Fraud - Credit Card/ATM",
    "0903": "Fraud - Impersonation",
    "0904": "Fraud - Wire/Computer",
    "1001": "Gambling - Bookmaking",
    "1002": "Gambling - Numbers",
    "1003": "Gambling - Other",
    "1101": "Homicide - Murder/Non-negligent Manslaughter",
    "1102": "Homicide - Negligent Manslaughter",
    "1103": "Homicide - Justifiable",
    "1201": "Human Trafficking - Commercial Sex Acts",
    "1202": "Human Trafficking - Involuntary Servitude",
    "1301": "Kidnapping/Abduction",
    "1401": "Larceny/Theft - Pocket-picking",
    "1402": "Larceny/Theft - Purse-snatching",
    "1403": "Larceny/Theft - Shoplifting",
    "1404": "Larceny/Theft - From Building",
    "1405": "Larceny/Theft - From Coin-Operated",
    "1406": "Larceny/Theft - From Motor Vehicle",
    "1407": "Larceny/Theft - Vehicle Parts",
    "1408": "Larceny/Theft - All Other",
    "1501": "Motor Vehicle Theft",
    "1502": "Motor Vehicle Theft - Recovery",
    "1601": "Pornography/Obscene Material",
    "1701": "Prostitution",
    "1702": "Prostitution - Assisting/Promoting",
    "1801": "Robbery - Highway",
    "1802": "Robbery - Commercial House",
    "1803": "Robbery - Gas Station",
    "1804": "Robbery - Convenience Store",
    "1805": "Robbery - Bank",
    "1806": "Robbery - Residence",
    "1807": "Robbery - Other",
    "1901": "Sex Offenses - Rape",
    "1902": "Sex Offenses - Sodomy",
    "1903": "Sex Offenses - Sexual Assault with Object",
    "1904": "Sex Offenses - Fondling",
    "2001": "Stolen Property - Receiving/Selling",
    "2101": "Weapon Law Violations",
    "2201": "Runaway",
    "2301": "Traffic - DUI/OWI",
    "2302": "Traffic - Hit and Run",
    "2303": "Traffic - Reckless Driving",
    "2304": "Traffic - Speeding",
    "2305": "Traffic - License Violations",
    "2306": "Traffic - Other",
    "2401": "Trespass of Real Property",
    "2501": "Disorderly Conduct",
    "2502": "Disturbing the Peace",
    "2503": "Drunk/Intoxicated",
    "2504": "Public Intoxication",
    "2505": "Loitering",
    "2601": "Family Offenses - Domestic Battery",
    "2602": "Family Offenses - Non-violent",
    "2701": "Peeping Tom",
    "2801": "Voyeurism",
    "2901": "Bribery",
    "3001": "Curfew Violation",
    "3101": "Liquor Law Violation",
    "3201": "Obstruction of Justice",
    "3202": "Resisting Arrest",
    "3203": "Escape from Custody",
    "3204": "Bail Jumping",
    "3301": "Child Abuse",
    "3302": "Child Neglect",
    "3303": "Child Abandonment",
    "3401": "Elder Abuse",
    "3402": "Elder Neglect",
    "3501": "Hate Crime - Race/Ethnicity",
    "3502": "Hate Crime - Religion",
    "3503": "Hate Crime - Sexual Orientation",
    "3504": "Hate Crime - Disability",
    "3505": "Hate Crime - Gender",
    "3601": "Stalking",
    "3701": "Terrorism",
    "3801": "Animal Cruelty",
    "3901": "Identity Theft",
    "4001": "Cybercrime - Hacking",
    "4002": "Cybercrime - Phishing",
    "4003": "Cybercrime - Identity Theft",
    "9999": "Other Offense (Not Classified)",
}

NCIC_VEHICLE_MAKES = {
    "AC": "Acura", "AM": "AM General", "AO": "Aston Martin", "AU": "Audi",
    "BM": "BMW", "BU": "Buick", "CA": "Cadillac", "CH": "Chevrolet",
    "CHR": "Chrysler", "DA": "Daewoo", "DG": "Dodge", "EG": "Eagle",
    "FD": "Ford", "FR": "Ferrari", "GE": "Geo", "GM": "GMC",
    "HD": "Harley-Davidson", "HN": "Honda", "HU": "Hummer", "HY": "Hyundai",
    "IN": "Infiniti", "IS": "Isuzu", "JA": "Jaguar", "JE": "Jeep",
    "KI": "Kia", "LA": "Lamborghini", "LR": "Land Rover", "LX": "Lexus",
    "LN": "Lincoln", "LT": "Lotus", "MA": "Mazda", "MC": "Mercedes-Benz",
    "MG": "MG", "MI": "Mini", "MT": "Mitsubishi", "NI": "Nissan",
    "OL": "Oldsmobile", "PL": "Plymouth", "PO": "Pontiac", "PR": "Porsche",
    "RA": "Ram", "RO": "Rolls-Royce", "SA": "Saab", "SC": "Saturn",
    "SM": "Smart", "SR": "Subaru", "SU": "Suzuki", "TE": "Tesla",
    "TO": "Toyota", "TR": "Triumph", "VO": "Volkswagen", "VL": "Volvo",
    "VW": "Volkswagen", "YU": "Yugo",
}


def lookup_ncic_code(code: str) -> str:
    return NCIC_OFFENSE_CODES.get(code, "")


def lookup_ncic_make(code: str) -> str:
    return NCIC_VEHICLE_MAKES.get(code.upper(), "")


def search_ncic(query: str, limit: int = 10) -> list:
    q = query.lower()
    results = []
    for code, desc in NCIC_OFFENSE_CODES.items():
        if q in code or q in desc.lower():
            results.append({"code": code, "description": desc})
    for code, name in NCIC_VEHICLE_MAKES.items():
        if q in code.lower() or q in name.lower():
            results.append({"code": code, "description": f"Vehicle Make: {name}"})
    return results[:limit]
