"use client";

import { useState } from "react";

interface DiffLine {
  type: "same" | "added" | "removed";
  text: string;
}

interface AuditResult {
  status: string;
  message?: string;
  diff?: DiffLine[];
  ai_draft_label?: string;
  final_label?: string;
}

export default function AIAuditTrailPage() {
  const [incidentId, setIncidentId] = useState("");
  const [loading, setLoading] = useState(false);
  const [auditData, setAuditData] = useState<AuditResult | null>(null);
  const [error, setError] = useState("");

  const fetchAuditDiff = async () => {
    if (!incidentId.trim()) {
      setError("Please enter an Incident ID.");
      return;
    }

    setLoading(true);
    setError("");
    setAuditData(null);

    try {
      const token = localStorage.getItem("chronos_token") || "";
      const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000"}/api/v1/audit/diff/${incidentId.trim()}`, {
        headers: {
          "Authorization": `Bearer ${token}`
        }
      });

      const data = await res.json();
      if (!res.ok || data.status === "error") {
        throw new Error(data.message || "Failed to fetch audit trail");
      }

      setAuditData(data);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-6 max-w-7xl mx-auto min-h-screen flex flex-col font-sans">
      <h1 className="text-3xl font-bold mb-2">Granular AI Audit Trail</h1>
      <p className="text-gray-600 mb-6">Trace exactly which words were generated by AI and which were edited by officers.</p>

      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4 font-medium">
          {error}
        </div>
      )}

      <div className="bg-white p-4 border rounded shadow-sm mb-6 flex gap-4 items-end">
        <div className="flex-1 max-w-md">
          <label className="block text-sm font-bold text-gray-700 mb-1">Incident ID</label>
          <input
            type="text"
            className="w-full p-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="e.g. INC-2026-001"
            value={incidentId}
            onChange={(e) => setIncidentId(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && fetchAuditDiff()}
          />
        </div>
        <button
          onClick={fetchAuditDiff}
          disabled={loading}
          className="bg-gray-800 text-white font-bold py-2 px-6 rounded shadow hover:bg-gray-900 disabled:opacity-50 transition"
        >
          {loading ? "Fetching..." : "View Audit Trail"}
        </button>
      </div>

      <div className="bg-white border rounded shadow-sm flex-1 flex flex-col min-h-[500px]">
        {!auditData && !loading && (
          <div className="flex-1 flex items-center justify-center text-gray-400 italic">
            Enter an incident ID to view the AI vs. Human text heatmap.
          </div>
        )}

        {loading && (
          <div className="flex-1 flex flex-col items-center justify-center text-gray-600">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gray-600 mb-4"></div>
            <p className="font-medium animate-pulse">Computing text diff...</p>
          </div>
        )}

        {auditData && auditData.diff && auditData.diff.length === 0 && (
          <div className="flex-1 flex items-center justify-center text-gray-500 italic p-6">
            {auditData.message || "No edits were made to the AI draft."}
          </div>
        )}

        {auditData && auditData.diff && auditData.diff.length > 0 && (
          <div className="flex flex-col h-full">
            <div className="bg-gray-50 border-b p-4 flex justify-between items-center">
              <div className="flex gap-6 text-sm font-medium">
                <div className="flex items-center gap-2">
                  <span className="w-3 h-3 bg-red-200 border border-red-500 rounded-full inline-block"></span>
                  <span className="text-gray-700">Removed (AI Original)</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="w-3 h-3 bg-green-200 border border-green-500 rounded-full inline-block"></span>
                  <span className="text-gray-700">Added (Human Edited)</span>
                </div>
              </div>
              <div className="text-xs text-gray-500 uppercase tracking-wider font-bold">
                {auditData.ai_draft_label} &rarr; {auditData.final_label}
              </div>
            </div>

            <div className="p-6 overflow-y-auto bg-gray-50/50 flex-1">
              <div className="font-mono text-sm leading-relaxed max-w-4xl mx-auto bg-white p-8 border rounded shadow-sm">
                {auditData.diff.map((line, idx) => {
                  if (line.type === "same") {
                    return <span key={idx} className="text-gray-800 break-words whitespace-pre-wrap">{line.text + "\n"}</span>;
                  }
                  if (line.type === "removed") {
                    return (
                      <span key={idx} className="bg-red-100 text-red-800 line-through px-1 rounded inline-block my-0.5 break-words whitespace-pre-wrap">
                        {line.text + "\n"}
                      </span>
                    );
                  }
                  if (line.type === "added") {
                    return (
                      <span key={idx} className="bg-green-100 text-green-900 border-b-2 border-green-400 px-1 rounded inline-block my-0.5 break-words whitespace-pre-wrap font-medium">
                        {line.text + "\n"}
                      </span>
                    );
                  }
                  return null;
                })}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
